version: "3"

services:
  postgresql:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: "skladok"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/skladok
    ports:
      - "5432:5432"

  my-app:
    build: .
    container_name: skladok-app
    ports:
      - "8080:8080"
    depends_on:
      - postgresql